import { describe, it } from 'node:test';
import { strict as assert } from 'node:assert';

// Imported from source (not the `@omadia/channel-sdk` dist barrel): these were
// added in #643, after the last dist build — same rationale as the #647
// provenance imports in channelApi/chatRouter.test.ts.
import {
  applyAiDisclosure,
  composeDisclosureText,
  DEFAULT_AI_DISCLOSURE_POLICY,
  InMemoryDisclosureSeenStore,
  type AiDisclosurePolicy,
  type DisclosureSeenStore,
} from '../packages/harness-channel-sdk/src/aiDisclosure.js';
import { toSemanticAnswer } from '../packages/harness-channel-sdk/src/toSemanticAnswer.js';
import type { ChatTurnResult } from '../packages/harness-channel-sdk/src/chatAgent.js';

const DE_STANDARD = 'Diese Antwort wurde von einem KI-System erzeugt.';
const EN_STANDARD = 'This response was generated by an AI system.';

// A minimal kernel-shaped result, mirroring the `base` used in
// orchestrator/directLine.test.ts.
const base: ChatTurnResult = { answer: 'Hallo.', toolCalls: 0, iterations: 0 };

const OPERATOR_OFF: AiDisclosurePolicy = { level: 'off', source: 'operator' };

describe('#643 composeDisclosureText — DE/EN, level, plain text', () => {
  it('composes the standard line in DE (the shipping default language)', () => {
    assert.equal(composeDisclosureText('de-DE', 'standard'), DE_STANDARD);
  });

  it('composes the standard line in EN', () => {
    assert.equal(composeDisclosureText('en-GB', 'standard'), EN_STANDARD);
  });

  it('composes the concise line in DE and EN', () => {
    assert.equal(composeDisclosureText('de', 'concise'), 'KI-generiert.');
    assert.equal(composeDisclosureText('en', 'concise'), 'AI-generated.');
  });

  it('falls back to DE for an unknown / absent locale — never an empty line', () => {
    assert.equal(composeDisclosureText('fr-FR', 'standard'), DE_STANDARD);
    assert.equal(composeDisclosureText(undefined, 'standard'), DE_STANDARD);
    assert.equal(composeDisclosureText('', 'standard'), DE_STANDARD);
  });

  it('weaves an operator-set assistant name into the standard line', () => {
    assert.equal(
      composeDisclosureText('de', 'standard', { assistantName: 'Omadia' }),
      'Diese Antwort wurde von Omadia, einem KI-System, erzeugt.',
    );
    assert.equal(
      composeDisclosureText('en', 'standard', { assistantName: 'Omadia' }),
      'This response was generated by Omadia, an AI system.',
    );
  });

  it('emits no markup a screen reader would trip on (single line, no markdown)', () => {
    for (const level of ['standard', 'concise'] as const) {
      for (const locale of ['de', 'en']) {
        const line = composeDisclosureText(locale, level);
        assert.doesNotMatch(line, /[*_`#<>|]/, 'no markdown control characters');
        assert.doesNotMatch(line, /[\r\n]/, 'single line');
      }
    }
  });
});

describe('#643 applyAiDisclosure — level resolution', () => {
  it('AC1: with no configuration at all, the answer carries the marking in text', () => {
    const { text, aiDisclosure } = applyAiDisclosure('Antwort.');
    assert.equal(text, `Antwort.\n\n${DE_STANDARD}`);
    assert.deepEqual(aiDisclosure, {
      text: DE_STANDARD,
      level: 'standard',
      locale: 'de',
      source: 'default',
    });
  });

  it('the shipping default is standard + active + source:default', () => {
    assert.deepEqual(DEFAULT_AI_DISCLOSURE_POLICY, {
      level: 'standard',
      source: 'default',
    });
    assert.throws(() => {
      // Frozen — no path may mutate the shared default.
      (DEFAULT_AI_DISCLOSURE_POLICY as { level: string }).level = 'off';
    });
  });

  it('resolves the concise level and the operator locale from the policy', () => {
    const { text, aiDisclosure } = applyAiDisclosure('A.', {
      policy: { level: 'concise', source: 'operator', locale: 'en' },
    });
    assert.equal(text, 'A.\n\nAI-generated.');
    assert.equal(aiDisclosure?.level, 'concise');
    assert.equal(aiDisclosure?.locale, 'en');
    assert.equal(aiDisclosure?.source, 'operator');
  });

  it('AC2: off is honoured only through explicit operator configuration', () => {
    const { text, aiDisclosure } = applyAiDisclosure('A.', { policy: OPERATOR_OFF });
    assert.equal(text, 'A.', 'no line folded in when the operator turned it off');
    assert.equal(aiDisclosure, undefined, 'and no structured field rides');
  });

  it('AC2: an off that is not operator-sourced is refused — falls back to the shipping default', () => {
    // The shipping default is never off, and a turn cannot silence itself: an
    // off policy without operator provenance is not a legitimate opt-out.
    const { text, aiDisclosure } = applyAiDisclosure('A.', {
      policy: { level: 'off', source: 'default' },
    });
    assert.equal(text, `A.\n\n${DE_STANDARD}`);
    assert.equal(aiDisclosure?.level, 'standard');
    assert.equal(aiDisclosure?.source, 'default');
  });

  it('reuses a pre-resolved disclosure verbatim and ignores the policy (single derivation)', () => {
    const preresolved = {
      text: 'Vorgegeben.',
      level: 'concise' as const,
      locale: 'de',
      source: 'operator' as const,
    };
    const { text, aiDisclosure } = applyAiDisclosure('A.', {
      disclosure: preresolved,
      policy: OPERATOR_OFF,
    });
    assert.equal(text, 'A.\n\nVorgegeben.');
    assert.deepEqual(aiDisclosure, preresolved);
  });

  it('folds onto an empty answer as the sole content', () => {
    assert.equal(applyAiDisclosure('').text, DE_STANDARD);
    assert.equal(applyAiDisclosure('   ').text, DE_STANDARD);
  });
});

describe('#643 applyAiDisclosure — fail-safe fold decision (AC3)', () => {
  it('folds when the scope is undeterminable: no scope, or no store', () => {
    assert.match(
      applyAiDisclosure('A.', { seen: new InMemoryDisclosureSeenStore() }).text,
      /KI-System/,
    );
    assert.match(applyAiDisclosure('A.', { scope: 's1' }).text, /KI-System/);
  });

  it('folds when the seen-store throws (restart / unknown backend / corrupt state)', () => {
    const throwing: DisclosureSeenStore = {
      hasSeen() {
        throw new Error('scope backend unavailable');
      },
      markSeen() {
        throw new Error('scope backend unavailable');
      },
    };
    const { text, aiDisclosure } = applyAiDisclosure('A.', { scope: 's1', seen: throwing });
    assert.equal(text, `A.\n\n${DE_STANDARD}`, 'a store error must fold, not omit');
    assert.ok(aiDisclosure, 'the structured field still rides');
  });

  it('folds on the first turn of a scope, suppresses it thereafter', () => {
    const seen = new InMemoryDisclosureSeenStore();
    const first = applyAiDisclosure('Turn 1.', { scope: 'conv-A', seen });
    const second = applyAiDisclosure('Turn 2.', { scope: 'conv-A', seen });
    assert.equal(first.text, `Turn 1.\n\n${DE_STANDARD}`, 'first turn folds');
    assert.equal(second.text, 'Turn 2.', 'later turn does not re-fold');
  });

  it('the structured field rides EVERY turn, even when the line is not folded', () => {
    const seen = new InMemoryDisclosureSeenStore();
    seen.markSeen('conv-B'); // scope already seen → no fold
    const { text, aiDisclosure } = applyAiDisclosure('Turn N.', { scope: 'conv-B', seen });
    assert.equal(text, 'Turn N.', 'not folded');
    assert.deepEqual(aiDisclosure, {
      text: DE_STANDARD,
      level: 'standard',
      locale: 'de',
      source: 'default',
    });
  });

  it('folds independently per scope', () => {
    const seen = new InMemoryDisclosureSeenStore();
    assert.match(applyAiDisclosure('A.', { scope: 'x', seen }).text, /KI-System/);
    assert.match(applyAiDisclosure('A.', { scope: 'y', seen }).text, /KI-System/);
    assert.doesNotMatch(applyAiDisclosure('A.', { scope: 'x', seen }).text, /KI-System/);
  });
});

describe('#643 toSemanticAnswer — carrier wiring, read back off the produced answer', () => {
  it('AC5: a bare legacy call is byte-for-byte unchanged (no ctx, no resolved marker)', () => {
    const sa = toSemanticAnswer(base);
    assert.equal(sa.text, 'Hallo.');
    assert.equal(sa.aiDisclosure, undefined);
  });

  it('AC1: opting in with no operator configuration folds the marking into text', () => {
    const sa = toSemanticAnswer(base, {});
    assert.equal(sa.text, `Hallo.\n\n${DE_STANDARD}`);
    assert.equal(sa.aiDisclosure?.level, 'standard');
    assert.equal(sa.aiDisclosure?.source, 'default');
  });

  it('AC2: an operator off produces no folded line and no structured field', () => {
    const sa = toSemanticAnswer(base, { policy: OPERATOR_OFF });
    assert.equal(sa.text, 'Hallo.');
    assert.equal(sa.aiDisclosure, undefined);
  });

  it('AC3: opting in with a scope but no seen-store folds (undeterminable → fold)', () => {
    const sa = toSemanticAnswer(base, { scope: 'conv-A' });
    assert.match(sa.text, /KI-System/);
  });

  it('forwards a marker the orchestrator pre-resolved on the result (#644 handoff)', () => {
    const r: ChatTurnResult = {
      ...base,
      aiDisclosure: {
        text: 'AI-generated.',
        level: 'concise',
        locale: 'en',
        source: 'operator',
      },
    };
    const sa = toSemanticAnswer(r);
    assert.equal(sa.aiDisclosure?.text, 'AI-generated.');
    assert.equal(sa.aiDisclosure?.source, 'operator');
    assert.match(sa.text, /AI-generated\./);
  });

  it('honours the seen-store threaded through the converter — suppresses the second turn', () => {
    const seen = new InMemoryDisclosureSeenStore();
    const first = toSemanticAnswer(base, { scope: 'conv-C', seen });
    const second = toSemanticAnswer(base, { scope: 'conv-C', seen });
    assert.match(first.text, /KI-System/);
    assert.doesNotMatch(second.text, /KI-System/);
    assert.ok(second.aiDisclosure, 'structured field still rides the suppressed turn');
  });

  it('additive: unrelated fields are untouched by the disclosure fold', () => {
    const r: ChatTurnResult = {
      ...base,
      verifier: {
        badge: 'verified',
        status: 'approved',
        claimCount: 1,
        contradictionCount: 0,
        unverifiedCount: 0,
        retryCount: 0,
        latencyMs: 5,
        mode: 'enforce',
      },
    };
    const sa = toSemanticAnswer(r, {});
    assert.equal(sa.verifier?.status, 'verified');
    assert.match(sa.text, /KI-System/);
  });

  it('folds AFTER the MCP-input prompt so both survive on a form-less channel', () => {
    const r: ChatTurnResult = {
      ...base,
      answer: '',
      pendingMcpInput: {
        correlationId: 'c1',
        serverName: 'AcmeMCP',
        serverId: 's1',
        toolName: 'lookup',
        fields: [{ name: 'q', required: true }],
      },
    };
    const sa = toSemanticAnswer(r, {});
    assert.match(sa.text, /AcmeMCP/, 'the MCP input prompt is still folded in');
    assert.match(sa.text, /KI-System/, 'and the disclosure rides after it');
    assert.ok(sa.text.indexOf('AcmeMCP') < sa.text.indexOf('KI-System'));
  });
});
